{
 "title": "cinemadash",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memória",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "Heap[MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"}) / 1024 / 1024",
     "legendFormat": "NonHeap[MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes) * 100 \r\n/ \r\nsum(jvm_memory_max_bytes)",
     "legendFormat": "% uso"
    }
   ]
  },
  {
   "title": "Tempo no ar",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa Erros [CREATE_MOVIE] último min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(movies_create_error_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Média tempo CREATE_MOVIE (ms)",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(movies_create_duration_seconds_sum[1m]) / rate(movies_create_duration_seconds_count[1m])*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Média de latência",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "Logs de [ERROR][WARN]",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", level=\"error\"}[5m]))",
     "legendFormat": "ERROR"
    },
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", level=\"warn\"}[5m]))",
     "legendFormat": "WARN"
    }
   ]
  },
  {
   "title": "ResponseTime Geral",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\",instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{url}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Iniciado em",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\",instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"$application\",instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\",instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "N. Timeouts com banco",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\",instance=\"$instance\", pool=\"$pool\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req/min geral",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões DB pool",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}