services:
  postgres:
    image: postgres:16
    container_name: cinemacidadedb
    environment:
      POSTGRES_DB: cinemacidade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinemanetwork

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-forum-api
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - cinemanetwork

  grafanacinema:
    image: grafana/grafana
    container_name: grafanacinema
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - cinemanetwork
    depends_on:
      - prometheus

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinemacidadeapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/cinemacidade
      - JAVA_TOOL_OPTIONS=-Xmx800m -Xms256m  # Heap abaixo do limite total
    mem_limit: 1024m      # Limite total de RAM
    cpus: 1.0            # Máximo core
    depends_on:
      - postgres
    networks:
      - cinemanetwork

volumes:
  postgres_data:

networks:
  cinemanetwork:
    driver: bridge
